"use client"
import Iconclose from '@/icon/iconclose'
import Icondeliveryinline from '@/icon/icondeliveryinline'
import React, { useState } from 'react'

export default function Updatedelivery() {
    const [ismodal, setismodal] = useState(false)
    return (
        <>
            <button className='btn btn-primary' onClick={() => setismodal(!ismodal)}>
                <Icondeliveryinline /> Update to Derivery
            </button>

            <div className={`modal ${ismodal ? 'show' : 'hide'}`} onClick={()=>setismodal(false)}>
                <div className="modal-content modal-md" onClick={()=>setismodal(true)}>
                    <div className="modal-header py-2"> 
                            <div className="flex justify-between items-center">
                                <h6>Title modal</h6> 
                                <button className='btn btn-error btn-sm' onClick={() => setismodal(!ismodal)}><Iconclose/></button>
                            </div> 
                    </div> 
                    <div className="modal-body">
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam optio, qui id voluptate quae porro exercitationem officiis inventore, similique minus quas vero nulla placeat animi pariatur omnis? Numquam, maiores vero?
                        Recusandae ratione laborum possimus maxime porro! Laboriosam eveniet sequi nisi. Optio, voluptatum quasi. Perferendis voluptas quod illum facere ducimus doloremque, maiores molestiae dicta minima suscipit amet, commodi asperiores ex adipisci.
                        Distinctio est cupiditate hic, rerum quod laudantium veniam nulla iure temporibus dignissimos, aliquam autem, perspiciatis quaerat velit tenetur nihil numquam? Consectetur quia sit magnam similique ducimus! Deleniti minima praesentium qui.
                        Nobis atque alias, officia possimus quos, assumenda sed id doloribus culpa tenetur nam praesentium velit dolore distinctio illum labore illo sit quia exercitationem. Dignissimos eum nostrum omnis ut, voluptas officia.
                        Accusamus, deleniti? Saepe repellat reiciendis quam dignissimos commodi? Autem cupiditate rem nam, ipsum harum natus ducimus quasi, voluptas nihil odio, ut explicabo dolore fuga quod! Tempore accusamus qui sit. Tenetur.
                        Aut dignissimos eligendi repellendus explicabo, ipsam magni, velit ullam consequatur accusantium necessitatibus sint corporis vel quos architecto harum. Fuga, tenetur voluptate error perspiciatis doloremque nam eveniet quisquam dolor pariatur ab!
                        Ex eveniet maxime officiis et dignissimos. Adipisci laborum esse eos ab ex nihil delectus officiis, minus consectetur autem iure neque necessitatibus repellat consequatur sed labore accusamus, id doloremque cupiditate. Enim!
                        Illo, in, fuga rem repellat asperiores vel impedit, iusto eaque ad dignissimos quos eligendi? Cupiditate delectus voluptatibus doloremque, officia necessitatibus recusandae veniam. Velit quae perspiciatis nulla reiciendis voluptatum! Delectus, qui.
                        Recusandae ex delectus, qui illum quas ratione quam sit optio, magnam quaerat quod dolorem sunt ea tenetur odio cupiditate perferendis, incidunt maiores praesentium accusantium! Quasi quae ab eligendi expedita minima?
                        Saepe aspernatur earum fuga quidem temporibus quo molestias dolore deleniti libero natus facilis nobis dolores et quis quas sunt, error sint inventore numquam dolor quos ipsum voluptate! Aspernatur, dolor adipisci.
                        Deserunt asperiores nisi veritatis velit eveniet voluptatem libero distinctio similique! Earum suscipit quia maxime illo! Laudantium nemo et voluptas exercitationem! Voluptatem veritatis libero, dicta corrupti recusandae numquam unde impedit doloremque.
                        Modi neque ea maiores non placeat nemo molestiae quae aspernatur, veritatis fuga consectetur aperiam, eveniet magni eaque laborum ipsam quas ab commodi culpa dolorem, perspiciatis est? Itaque assumenda voluptatibus porro.
                        Neque iure nemo inventore aliquam est fugiat impedit officiis quod, nesciunt a numquam blanditiis, quia provident, rem esse recusandae dolorum atque fugit aliquid quidem natus officia eos sequi expedita. Necessitatibus.
                        Ex id aperiam eveniet, labore illum consequuntur vero beatae dolores exercitationem distinctio ratione hic tempora possimus, at odit sapiente laborum commodi? Dignissimos autem sequi consectetur repellat nihil voluptatum voluptatem praesentium?
                        Cum, expedita ducimus eos incidunt aliquam voluptate quos reiciendis ipsa explicabo nesciunt et blanditiis corporis fugiat saepe ipsum in debitis doloremque laudantium numquam eligendi architecto assumenda. Natus eius nostrum distinctio?
                        Magnam neque quidem perferendis assumenda, tempore placeat unde dignissimos architecto veniam eius. Eaque molestias at enim dolor voluptate voluptatum atque ea. Perferendis quibusdam assumenda maiores officiis, molestiae totam quos explicabo?
                        Ipsum temporibus, sequi velit, dolor debitis atque recusandae unde vitae eaque illum ratione explicabo error architecto distinctio qui consequatur ea dolorem, iste possimus magnam eligendi eum provident. Laborum, omnis rerum.
                        Dolorum facilis dolores ex assumenda culpa quod repellendus ratione ipsam enim, quam dicta veniam quaerat consequuntur, voluptatum illum dolorem. Corporis numquam ea explicabo architecto incidunt cumque, a dolorum quam saepe!
                        Nostrum qui iste mollitia. Voluptate dignissimos maiores nisi. Quae accusantium sit, sunt quo, natus voluptatibus ut dolor nesciunt perferendis aliquam, explicabo quod architecto molestiae eligendi! Modi atque aspernatur doloremque consequatur.
                        Eius optio officiis rem consequuntur sunt! Quos praesentium minus, omnis nobis porro placeat quibusdam saepe officiis suscipit quidem fuga perspiciatis ut tempore quo commodi debitis ab. Rem voluptates tempora perspiciatis!
                        Incidunt repellendus rerum laboriosam in quaerat perferendis. Repudiandae doloribus nesciunt itaque, facere exercitationem alias necessitatibus neque aliquam ex. Explicabo, sit provident quae laboriosam consectetur aliquid commodi tenetur quaerat delectus omnis?
                        Ullam pariatur maiores iusto totam laudantium obcaecati molestias officia iure optio. Eligendi similique itaque qui ipsa dolore laborum fugiat vero, labore, reiciendis ipsam optio dolor. Saepe magnam tenetur numquam laboriosam!
                        Cum, expedita ducimus eos incidunt aliquam voluptate quos reiciendis ipsa explicabo nesciunt et blanditiis corporis fugiat saepe ipsum in debitis doloremque laudantium numquam eligendi architecto assumenda. Natus eius nostrum distinctio?
                        Magnam neque quidem perferendis assumenda, tempore placeat unde dignissimos architecto veniam eius. Eaque molestias at enim dolor voluptate voluptatum atque ea. Perferendis quibusdam assumenda maiores officiis, molestiae totam quos explicabo?
                        Ipsum temporibus, sequi velit, dolor debitis atque recusandae unde vitae eaque illum ratione explicabo error architecto distinctio qui consequatur ea dolorem, iste possimus magnam eligendi eum provident. Laborum, omnis rerum.
                        Dolorum facilis dolores ex assumenda culpa quod repellendus ratione ipsam enim, quam dicta veniam quaerat consequuntur, voluptatum illum dolorem. Corporis numquam ea explicabo architecto incidunt cumque, a dolorum quam saepe!
                        Nostrum qui iste mollitia. Voluptate dignissimos maiores nisi. Quae accusantium sit, sunt quo, natus voluptatibus ut dolor nesciunt perferendis aliquam, explicabo quod architecto molestiae eligendi! Modi atque aspernatur doloremque consequatur.
                        Eius optio officiis rem consequuntur sunt! Quos praesentium minus, omnis nobis porro placeat quibusdam saepe officiis suscipit quidem fuga perspiciatis ut tempore quo commodi debitis ab. Rem voluptates tempora perspiciatis!
                        Incidunt repellendus rerum laboriosam in quaerat perferendis. Repudiandae doloribus nesciunt itaque, facere exercitationem alias necessitatibus neque aliquam ex. Explicabo, sit provident quae laboriosam consectetur aliquid commodi tenetur quaerat delectus omnis?
                        Ullam pariatur maiores iusto totam laudantium obcaecati molestias officia iure optio. Eligendi similique itaque qui ipsa dolore laborum fugiat vero, labore, reiciendis ipsam optio dolor. Saepe magnam tenetur numquam laboriosam!
                        Ipsum temporibus, sequi velit, dolor debitis atque recusandae unde vitae eaque illum ratione explicabo error architecto distinctio qui consequatur ea dolorem, iste possimus magnam eligendi eum provident. Laborum, omnis rerum.
                        Dolorum facilis dolores ex assumenda culpa quod repellendus ratione ipsam enim, quam dicta veniam quaerat consequuntur, voluptatum illum dolorem. Corporis numquam ea explicabo architecto incidunt cumque, a dolorum quam saepe!
                        Nostrum qui iste mollitia. Voluptate dignissimos maiores nisi. Quae accusantium sit, sunt quo, natus voluptatibus ut dolor nesciunt perferendis aliquam, explicabo quod architecto molestiae eligendi! Modi atque aspernatur doloremque consequatur.
                        Eius optio officiis rem consequuntur sunt! Quos praesentium minus, omnis nobis porro placeat quibusdam saepe officiis suscipit quidem fuga perspiciatis ut tempore quo commodi debitis ab. Rem voluptates tempora perspiciatis!
                        Incidunt repellendus rerum laboriosam in quaerat perferendis. Repudiandae doloribus nesciunt itaque, facere exercitationem alias necessitatibus neque aliquam ex. Explicabo, sit provident quae laboriosam consectetur aliquid commodi tenetur quaerat delectus omnis?
                        Ullam pariatur maiores iusto totam laudantium obcaecati molestias officia iure optio. Eligendi similique itaque qui ipsa dolore laborum fugiat vero, labore, reiciendis ipsam optio dolor. Saepe magnam tenetur numquam laboriosam!
                        Ipsum temporibus, sequi velit, dolor debitis atque recusandae unde vitae eaque illum ratione explicabo error architecto distinctio qui consequatur ea dolorem, iste possimus magnam eligendi eum provident. Laborum, omnis rerum.
                        Dolorum facilis dolores ex assumenda culpa quod repellendus ratione ipsam enim, quam dicta veniam quaerat consequuntur, voluptatum illum dolorem. Corporis numquam ea explicabo architecto incidunt cumque, a dolorum quam saepe!
                        Nostrum qui iste mollitia. Voluptate dignissimos maiores nisi. Quae accusantium sit, sunt quo, natus voluptatibus ut dolor nesciunt perferendis aliquam, explicabo quod architecto molestiae eligendi! Modi atque aspernatur doloremque consequatur.
                        Eius optio officiis rem consequuntur sunt! Quos praesentium minus, omnis nobis porro placeat quibusdam saepe officiis suscipit quidem fuga perspiciatis ut tempore quo commodi debitis ab. Rem voluptates tempora perspiciatis!
                        Incidunt repellendus rerum laboriosam in quaerat perferendis. Repudiandae doloribus nesciunt itaque, facere exercitationem alias necessitatibus neque aliquam ex. Explicabo, sit provident quae laboriosam consectetur aliquid commodi tenetur quaerat delectus omnis?
                        Ullam pariatur maiores iusto totam laudantium obcaecati molestias officia iure optio. Eligendi similique itaque qui ipsa dolore laborum fugiat vero, labore, reiciendis ipsam optio dolor. Saepe magnam tenetur numquam laboriosam!
                        Ipsum temporibus, sequi velit, dolor debitis atque recusandae unde vitae eaque illum ratione explicabo error architecto distinctio qui consequatur ea dolorem, iste possimus magnam eligendi eum provident. Laborum, omnis rerum.
                        Dolorum facilis dolores ex assumenda culpa quod repellendus ratione ipsam enim, quam dicta veniam quaerat consequuntur, voluptatum illum dolorem. Corporis numquam ea explicabo architecto incidunt cumque, a dolorum quam saepe!
                        Nostrum qui iste mollitia. Voluptate dignissimos maiores nisi. Quae accusantium sit, sunt quo, natus voluptatibus ut dolor nesciunt perferendis aliquam, explicabo quod architecto molestiae eligendi! Modi atque aspernatur doloremque consequatur.
                        Eius optio officiis rem consequuntur sunt! Quos praesentium minus, omnis nobis porro placeat quibusdam saepe officiis suscipit quidem fuga perspiciatis ut tempore quo commodi debitis ab. Rem voluptates tempora perspiciatis!
                        Incidunt repellendus rerum laboriosam in quaerat perferendis. Repudiandae doloribus nesciunt itaque, facere exercitationem alias necessitatibus neque aliquam ex. Explicabo, sit provident quae laboriosam consectetur aliquid commodi tenetur quaerat delectus omnis?
                        Ullam pariatur maiores iusto totam laudantium obcaecati molestias officia iure optio. Eligendi similique itaque qui ipsa dolore laborum fugiat vero, labore, reiciendis ipsam optio dolor. Saepe magnam tenetur numquam laboriosam!
                        Ullam pariatur maiores iusto totam laudantium obcaecati molestias officia iure optio. Eligendi similique itaque qui ipsa dolore laborum fugiat vero, labore, reiciendis ipsam optio dolor. Saepe magnam tenetur numquam laboriosam!
                        Ipsum temporibus, sequi velit, dolor debitis atque recusandae unde vitae eaque illum ratione explicabo error architecto distinctio qui consequatur ea dolorem, iste possimus magnam eligendi eum provident. Laborum, omnis rerum.
                        Dolorum facilis dolores ex assumenda culpa quod repellendus ratione ipsam enim, quam dicta veniam quaerat consequuntur, voluptatum illum dolorem. Corporis numquam ea explicabo architecto incidunt cumque, a dolorum quam saepe!
                        Nostrum qui iste mollitia. Voluptate dignissimos maiores nisi. Quae accusantium sit, sunt quo, natus voluptatibus ut dolor nesciunt perferendis aliquam, explicabo quod architecto molestiae eligendi! Modi atque aspernatur doloremque consequatur.
                        Eius optio officiis rem consequuntur sunt! Quos praesentium minus, omnis nobis porro placeat quibusdam saepe officiis suscipit quidem fuga perspiciatis ut tempore quo commodi debitis ab. Rem voluptates tempora perspiciatis!
                        Incidunt repellendus rerum laboriosam in quaerat perferendis. Repudiandae doloribus nesciunt itaque, facere exercitationem alias necessitatibus neque aliquam ex. Explicabo, sit provident quae laboriosam consectetur aliquid commodi tenetur quaerat delectus omnis?
                        Ullam pariatur maiores iusto totam laudantium obcaecati molestias officia iure optio. Eligendi similique itaque qui ipsa dolore laborum fugiat vero, labore, reiciendis ipsam optio dolor. Saepe magnam tenetur numquam laboriosam!
                        Ullam pariatur maiores iusto totam laudantium obcaecati molestias officia iure optio. Eligendi similique itaque qui ipsa dolore laborum fugiat vero, labore, reiciendis ipsam optio dolor. Saepe magnam tenetur numquam laboriosam!
                        Ipsum temporibus, sequi velit, dolor debitis atque recusandae unde vitae eaque illum ratione explicabo error architecto distinctio qui consequatur ea dolorem, iste possimus magnam eligendi eum provident. Laborum, omnis rerum.
                        Dolorum facilis dolores ex assumenda culpa quod repellendus ratione ipsam enim, quam dicta veniam quaerat consequuntur, voluptatum illum dolorem. Corporis numquam ea explicabo architecto incidunt cumque, a dolorum quam saepe!
                        Nostrum qui iste mollitia. Voluptate dignissimos maiores nisi. Quae accusantium sit, sunt quo, natus voluptatibus ut dolor nesciunt perferendis aliquam, explicabo quod architecto molestiae eligendi! Modi atque aspernatur doloremque consequatur.
                        Eius optio officiis rem consequuntur sunt! Quos praesentium minus, omnis nobis porro placeat quibusdam saepe officiis suscipit quidem fuga perspiciatis ut tempore quo commodi debitis ab. Rem voluptates tempora perspiciatis!
                        Incidunt repellendus rerum laboriosam in quaerat perferendis. Repudiandae doloribus nesciunt itaque, facere exercitationem alias necessitatibus neque aliquam ex. Explicabo, sit provident quae laboriosam consectetur aliquid commodi tenetur quaerat delectus omnis?
                        Ullam pariatur maiores iusto totam laudantium obcaecati molestias officia iure optio. Eligendi similique itaque qui ipsa dolore laborum fugiat vero, labore, reiciendis ipsam optio dolor. Saepe magnam tenetur numquam laboriosam!
                        Ullam pariatur maiores iusto totam laudantium obcaecati molestias officia iure optio. Eligendi similique itaque qui ipsa dolore laborum fugiat vero, labore, reiciendis ipsam optio dolor. Saepe magnam tenetur numquam laboriosam!
                        Ipsum temporibus, sequi velit, dolor debitis atque recusandae unde vitae eaque illum ratione explicabo error architecto distinctio qui consequatur ea dolorem, iste possimus magnam eligendi eum provident. Laborum, omnis rerum.
                        Dolorum facilis dolores ex assumenda culpa quod repellendus ratione ipsam enim, quam dicta veniam quaerat consequuntur, voluptatum illum dolorem. Corporis numquam ea explicabo architecto incidunt cumque, a dolorum quam saepe!
                        Nostrum qui iste mollitia. Voluptate dignissimos maiores nisi. Quae accusantium sit, sunt quo, natus voluptatibus ut dolor nesciunt perferendis aliquam, explicabo quod architecto molestiae eligendi! Modi atque aspernatur doloremque consequatur.
                        Eius optio officiis rem consequuntur sunt! Quos praesentium minus, omnis nobis porro placeat quibusdam saepe officiis suscipit quidem fuga perspiciatis ut tempore quo commodi debitis ab. Rem voluptates tempora perspiciatis!
                        Incidunt repellendus rerum laboriosam in quaerat perferendis. Repudiandae doloribus nesciunt itaque, facere exercitationem alias necessitatibus neque aliquam ex. Explicabo, sit provident quae laboriosam consectetur aliquid commodi tenetur quaerat delectus omnis?
                        Ullam pariatur maiores iusto totam laudantium obcaecati molestias officia iure optio. Eligendi similique itaque qui ipsa dolore laborum fugiat vero, labore, reiciendis ipsam optio dolor. Saepe magnam tenetur numquam laboriosam!
                        Ipsum temporibus, sequi velit, dolor debitis atque recusandae unde vitae eaque illum ratione explicabo error architecto distinctio qui consequatur ea dolorem, iste possimus magnam eligendi eum provident. Laborum, omnis rerum.
                        Dolorum facilis dolores ex assumenda culpa quod repellendus ratione ipsam enim, quam dicta veniam quaerat consequuntur, voluptatum illum dolorem. Corporis numquam ea explicabo architecto incidunt cumque, a dolorum quam saepe!
                        Nostrum qui iste mollitia. Voluptate dignissimos maiores nisi. Quae accusantium sit, sunt quo, natus voluptatibus ut dolor nesciunt perferendis aliquam, explicabo quod architecto molestiae eligendi! Modi atque aspernatur doloremque consequatur.
                        Eius optio officiis rem consequuntur sunt! Quos praesentium minus, omnis nobis porro placeat quibusdam saepe officiis suscipit quidem fuga perspiciatis ut tempore quo commodi debitis ab. Rem voluptates tempora perspiciatis!
                        Incidunt repellendus rerum laboriosam in quaerat perferendis. Repudiandae doloribus nesciunt itaque, facere exercitationem alias necessitatibus neque aliquam ex. Explicabo, sit provident quae laboriosam consectetur aliquid commodi tenetur quaerat delectus omnis?
                        Ullam pariatur maiores iusto totam laudantium obcaecati molestias officia iure optio. Eligendi similique itaque qui ipsa dolore laborum fugiat vero, labore, reiciendis ipsam optio dolor. Saepe magnam tenetur numquam laboriosam!
                        Cum, expedita ducimus eos incidunt aliquam voluptate quos reiciendis ipsa explicabo nesciunt et blanditiis corporis fugiat saepe ipsum in debitis doloremque laudantium numquam eligendi architecto assumenda. Natus eius nostrum distinctio?
                        Magnam neque quidem perferendis assumenda, tempore placeat unde dignissimos architecto veniam eius. Eaque molestias at enim dolor voluptate voluptatum atque ea. Perferendis quibusdam assumenda maiores officiis, molestiae totam quos explicabo?
                        Ipsum temporibus, sequi velit, dolor debitis atque recusandae unde vitae eaque illum ratione explicabo error architecto distinctio qui consequatur ea dolorem, iste possimus magnam eligendi eum provident. Laborum, omnis rerum.
                        Dolorum facilis dolores ex assumenda culpa quod repellendus ratione ipsam enim, quam dicta veniam quaerat consequuntur, voluptatum illum dolorem. Corporis numquam ea explicabo architecto incidunt cumque, a dolorum quam saepe!
                        Nostrum qui iste mollitia. Voluptate dignissimos maiores nisi. Quae accusantium sit, sunt quo, natus voluptatibus ut dolor nesciunt perferendis aliquam, explicabo quod architecto molestiae eligendi! Modi atque aspernatur doloremque consequatur.
                        Eius optio officiis rem consequuntur sunt! Quos praesentium minus, omnis nobis porro placeat quibusdam saepe officiis suscipit quidem fuga perspiciatis ut tempore quo commodi debitis ab. Rem voluptates tempora perspiciatis!
                        Incidunt repellendus rerum laboriosam in quaerat perferendis. Repudiandae doloribus nesciunt itaque, facere exercitationem alias necessitatibus neque aliquam ex. Explicabo, sit provident quae laboriosam consectetur aliquid commodi tenetur quaerat delectus omnis?
                        Ullam pariatur maiores iusto totam laudantium obcaecati molestias officia iure optio. Eligendi similique itaque qui ipsa dolore laborum fugiat vero, labore, reiciendis ipsam optio dolor. Saepe magnam tenetur numquam laboriosam!
                    </div>
                </div>
            </div>
        </>
    )
}
